use_frameworks!

platform :ios, '11.0'

target 'OpenAttestationIOS_Example' do
  pod 'OpenAttestationIOS', :path => '../'

  target 'OpenAttestationIOS_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
